name: SurvivalGame
main: SurvivalGame\Main
version: "1.0.3"
api: [1.0.0]
load: POSTWORLD
author: Driesboy
commands:
 fsg:
  permission: FSurvivalGame.command.fsg
  description: FSurvivalGame Main Command
  usage: /fsg <set|remove>
 lobby:
  permission: FSurvivalGame.command.lobby
  description: back to lobby
  usage: /lobby
permissions:
 FSurvivalGame.*:
  description: the main permission
  default: op
  children:
   FSurvivalGame.command.*:
    description: use commands in plugin
    default: op
    children:
     FSurvivalGame.command.lobby:
      description: back to lobby
      default: true
     FSurvivalGame.command.fsg:
      description: set SurvivalGame
      default: op
   FSurvivalGame.touch.startgame:
    description: click the sign and join the game
    default: true
